apiVersion: v1
items:
- apiVersion: consul.hashicorp.com/v1alpha1
  kind: ServiceIntentions
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"consul.hashicorp.com/v1alpha1","kind":"ServiceIntentions","metadata":{"annotations":{},"name":"frontend-default-to-backend-second","namespace":"default"},"spec":{"destination":{"name":"backend"},"sources":[{"action":"allow","name":"frontend","partition":"default"}]}}
    creationTimestamp: "2023-03-22T17:31:52Z"
    deletionGracePeriodSeconds: 0
    deletionTimestamp: "2023-03-24T11:24:01Z"
    finalizers:
    - finalizers.consul.hashicorp.com
    generation: 2
    name: frontend-default-to-backend-second
    namespace: default
    resourceVersion: "223528"
    uid: 8a411bcf-be2f-44e4-bdba-b2f880c25f86
  spec:
    destination:
      name: backend
      namespace: default
    sources:
    - action: allow
      name: frontend
      partition: default
  status:
    conditions:
    - lastTransitionTime: "2023-03-24T10:32:53Z"
      status: "True"
      type: Synced
    lastSyncedTime: "2023-03-24T10:32:53Z"
kind: List
metadata:
  resourceVersion: ""
