apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: dcanadillas-demo
    tier: backend
spec:
  selector:
    myapp: dcanadillas-demo
    tier: backend
  ports:
  - protocol: TCP
    port: 8080
    targetPort: http
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend
  labels:
    app: dcanadillas-demo
    tier: back
---
# This file configures the hello-world app which serves public web traffic.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: dcanadillas-demo
    myapp: dcanadillas-demo
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      myapp: dcanadillas-demo
      tier: backend
  template:
    metadata:
      labels:
        app: dcanadillas-demo
        myapp: dcanadillas-demo
        tier: backend
      annotations:
        consul.hashicorp.com/connect-inject: "true"
        consul.hashicorp.com/connect-service: "backend"
    spec:
      serviceAccount: backend
      containers:
      - name: backend
        image: hcdcanadillas/pydemo-back:v1.2
        imagePullPolicy: Always
        ports:
          - name: http
            containerPort: 8080
        env:
          # %{ for k,v in entrypoint.env }
          # - name: ${k}
          #   value: "${v}"
          # %{ endfor }
          - name: PORT
            value: "8080"
          - name: TARGET
            value: "World DC2"