apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: apigw-to-frontend
spec:
  destination:
    name: frontend
  sources:
   - name: api-gateway
     action: allow
     partition: default
